apiVersion: apps/v1
kind: Deployment
metadata:
  name: pl-samplewebapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pl-samplewebapi
  template:
    metadata:
      labels:
        app: pl-samplewebapi
    spec:
      containers:
        - name: pl-samplewebapi
          image: plsamplewebapi.azurecr.io/plsamplewebapi:latest
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pl-samplewebapi
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: pl-samplewebapi
