apiVersion: apps/v1
kind: Deployment
metadata:
  name: pl-samplewebapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pl-samplewebapi
  template:
    metadata:
      labels:
        app: pl-samplewebapi
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: pl-samplewebapi
        image: plsamplewebapi.azurecr.io/plsamplewebapi:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pl-samplewebapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: pl-samplewebapi
